"""followers

Revision ID: 558f73a2f5e4
Revises: 0d3653d5c9a7
Create Date: 2021-09-07 22:28:40.421066

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '558f73a2f5e4'
down_revision = '0d3653d5c9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
